config/routes.rb
Rails.application.routes.draw do
  get 'impressum/about'

  get 'impressum/support'

  get '/fleamarket' => 'impressum#fleamarket'

  root :to => 'items#index'
  get 'openjub'  => redirect("https://api.jacobs-cs.club/view/login")
  post '/login'   => 'sessions#create'
  get '/logout' => 'sessions#destroy'
  get '/users/:id', to: 'users#show', as:'user'
  get '/admin/users' => 'users#admin' #table of users
  get '/admin/category' => 'category#index'
  get '/admin/:user_id/items/new' => 'items#new_admin'
  post '/admin/:user_id/items' => 'items#create_admin'
  get '/admin/make_admin/:user_id' => 'users#make_admin'
  get '/admin/make_user/:user_id' => 'users#make_user'
  get '/items' => 'items#index'
  get '/items/new' => 'items#new'
  post '/items' => 'items#create'
  get '/items/user/:id' => 'items#user_items'
  get '/items/:id' => 'items#show'
  get '/items/:id/edit' => 'items#edit', :as => :item
  patch '/items/:id/edit' => 'items#update'
  get '/items/:id/delete' => 'items#delete'
  resources :users
  resources :transactions, only: [:new, :create]

  get '/category' => redirect('/admin/category')
  post '/categories' => 'category#create'
  get '/category/:id/delete' => 'category#delete'
  patch '/category' => 'category#update'
  get '/category/:machine_name' =>'items#index'

end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  #before_action: authenticate_user!

  def new
    gon.client_token = generate_client_token
    render :new
  end
 
  def create
    @result = Braintree::Transaction.sale(
              amount: $price,
              payment_method_nonce: params[:payment_method_nonce])
    if @result.success?
      redirect_to items_path, notice: "Congratulations! Your transaction has been successful!"
    else
      flash[:alert] = "Something went wrong while processing your transaction. Please try again!"
      gon.client_token = generate_client_token
      render :new
    end
  end

  private
  def generate_client_token
    Braintree::ClientToken.generate
  end
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/views/transactions/new.html.erb
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
<div class="container">
  <div>
	<div class="col-xs-9 col-md-9">
		<h1 class="text-center">Transactions</h1>
		<div class="form-container radius-box glassy-bg small-10 small-centered medium-8 large-6 columns">
		<h2 class="mbs">New Transaction</h2>
		<%= form_tag transactions_path do%>
		  <p>Please enter your payment details:</p>
		  <div id="dropin"></div>
   		  <%=submit_tag "Pay #{$price}", class: "button mt1" %>
		<%end%>
		</div>
	</div>
  </div>
</div>