config/routes.rb
Rails.application.routes.draw do
  get 'impressum/about'

  get 'impressum/support'

  get '/fleamarket' => 'impressum#fleamarket'

  root :to => 'items#index'
  get 'openjub'  => redirect("https://api.jacobs-cs.club/view/login")
  post '/login'   => 'sessions#create'
  get '/logout' => 'sessions#destroy'
  get '/users/:id', to: 'users#show', as:'user'
  get '/admin/users' => 'users#admin' #table of users
  get '/admin/category' => 'category#index'
  get '/admin/:user_id/items/new' => 'items#new_admin'
  post '/admin/:user_id/items' => 'items#create_admin'
  get '/admin/make_admin/:user_id' => 'users#make_admin'
  get '/admin/make_user/:user_id' => 'users#make_user'
  get '/items' => 'items#index'
  get '/items/new' => 'items#new'
  post '/items' => 'items#create'
  get '/items/user/:id' => 'items#user_items'
  get '/items/:id' => 'items#show'
  get '/items/:id/edit' => 'items#edit', :as => :item
  patch '/items/:id/edit' => 'items#update'
  get '/items/:id/delete' => 'items#delete'
  resources :users
  resources :transactions, only: [:new, :create]

  get '/category' => redirect('/admin/category')
  post '/categories' => 'category#create'
  get '/category/:id/delete' => 'category#delete'
  patch '/category' => 'category#update'
  get '/category/:machine_name' =>'items#index'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>JacobsMKT</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= include_gon(:init => true) %>
    <%= stylesheet_link_tag "application" %>
    <%= csrf_meta_tags %>
    <link rel="stylesheet" href="/css/bootstrap.config.css">
    <link href='https://fonts.googleapis.com/css?family=Pacifico' rel='stylesheet' type='text/css'>
    <script src="/script/prefixfree.min.js"></script>
</head>
    <body>      
      <!-- <div class="ribbon"><span>endorsed by USG</span></div> -->

      <header id="custom-bootstrap-menu" role="banner" class="navbar navbar-default">
        <div class="container">
          <div class="navbar-header">     
            <a class="name navbar-brand" href="/" title="Home">Jacobs Market</a>
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
          </div>

          <div class="navbar-collapse collapse">
            <nav role="navigation">
              <ul class="menu nav navbar-nav">
                <li><a href="/" class="active">Home</a></li>
                <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-hashpopup="true"
                  aria-expanded="false">Categories<span class="caret"></span></a>
                  <ul class="dropdown-menu">
                    <% Category.all.each do |category| %>
                      <li><a href="/category/<%= category.machine_name %>"><%= category.name %></a></li>
                    <% end %>
                  </ul>
                </li>
                <li><a href="/fleamarket" class="active">Flea Market</a></li>
              </ul>
            </nav>
            <nav>                               
              
              <form class="navbar-form navbar-right">
                <% if logged_in? %>
                  <%= link_to 'My Account', user_path(@current_user), :class => "btn btn-success"%>
                  <a class="btn btn-success" href="/logout">Log out</a>
                <% else %>
                  <%= link_to "Log in", openjub_path, :class => "btn btn-success", :method => :get, :target => "_blank" %>
                <% end %>   
              </form>
            </nav>
            <div style="width:100px"></div>
          </div>
        </div>
      </header>

    <% flash.each do |message_type, message| %>
      <div class="container">
        <div>
          <div class="col-xs-12 col-md-12">  
            <div class="alert alert-<%=message_type%> alert-dismissible" role="alert">
              <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
              <center><%= message %></center>
            </div>
          </div>
        </div>
      </div>
    <% end %>
 
    <div class="side-menu">
    </div>

    <div class="main-container">
      <%= yield %>
    </div>

    <!-- Footer -->
    <%= debug(params) if Rails.env.development? %>
    <div class="footer">
      <div class="container">
        <div>
          <ul class="list-inline">
            <li><%= link_to "About", "/impressum/about"%></li> 
            <li><%= link_to "Privacy", "/privacy_policy.pdf" %></li> 
            <li><%= link_to "Support", "/impressum/support" %></li> 
          </ul>
        </div>
        <p class="pull-left">©2014-2015 The Jakeup Team. All rights reserved.</p>
      </div>
    </div>
    <% unless logged_in? %>
    <script>
      var once = false;
      //get the callback from openJUB
      window.addEventListener("message", receiveMessage, false);

      function post(data) {

        $.ajax({
          url: "/login",
          type: "POST",
          data: JSON.parse(data),
          success: function(){console.log("submitted")}
        });

      }

      function receiveMessage(event) {
        if(!once) {
          once = true;
          console.log(event);
          post(event.data);
          console.log("posted");
        }
      }
    </script>
    <% end %>
  </body>
</html>